# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e8d994ab-8dd7-4775-a246-5c607dd3da5f";
      fsType = "btrfs";
      options = ["compress=zstd"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5707-83F3";
      fsType = "vfat";
    };

  fileSystems."/games" =
    {
      device = "/dev/disk/by-uuid/f080f2c6-4bc3-4682-9dd2-3e554a76884a";
      fsType = "xfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6b6d027f-217e-4ff3-aaf2-c4b61cc57747"; }
    ];


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
